/* The four layouts, wired to the demo entities from demo-hass.js. */
const heatpump = {
  name: "Heat pump",
  entity: "switch.heat_pump",
  state_entity: "binary_sensor.compressor",
  mode: "sensor.hp_operating_mode",
  power: "sensor.hp_power",
  cop: "sensor.hp_cop",
  flow_temp: "sensor.hp_flow_temperature",
  return_temp: "sensor.hp_return_temperature",
  outside_temp: "sensor.outside_temperature",
  compressor: "sensor.compressor_load",
  mode: "select.system_mode",
  flow_rate: "sensor.hp_flow_rate",
};

const buffer = {
  name: "Buffer tank",
  top: "sensor.buffer_top",
  middle: "sensor.buffer_middle",
  bottom: "sensor.buffer_bottom",
  charge: "sensor.buffer_charge",
};

const radiators = {
  name: "Radiators, ground floor",
  type: "radiator",
  entity: "switch.circuit_a",
  flow_temp: "sensor.circuit_a_flow",
  return_temp: "sensor.circuit_a_return",
  room_temp: "sensor.living_room_temperature",
  pump: "binary_sensor.circuit_a_pump",
  valve: "sensor.circuit_a_mixer",
  mode: "climate.circuit_a",
  target_temp: "climate.circuit_a",
};

const underfloor = {
  name: "Underfloor heating, first floor",
  type: "underfloor",
  entity: "switch.circuit_b",
  flow_temp: "sensor.circuit_b_flow",
  return_temp: "sensor.circuit_b_return",
  room_temp: "sensor.bathroom_temperature",
  pump: "binary_sensor.circuit_b_pump",
  valve: "sensor.circuit_b_mixer",
};

window.previewConfigs = {
  extras: {
    type: "custom:heatpump-flow-card",
    layout: "dhw-dual",
    title: "Defrosting, with the element in the tank running",
    heatpump: {
      ...heatpump,
      status: "sensor.hp_status",
      aux_heat: "binary_sensor.aux_heat",
      aux_heat_power: "sensor.aux_heat_power",
    },
    buffer: {
      ...buffer,
      heater: { entity: "switch.tank_heater", name: "AC-Thor" },
      heater_power: "sensor.tank_heater_power",
      heater_temp: "sensor.tank_heater_temperature",
      heater_mode: "select.tank_heater_mode",
    },
    dhw: {
      name: "Hot water",
      entity: "switch.hot_water",
      temp: "sensor.dhw_temperature",
      target_temp: "number.dhw_setpoint",
      pump: "binary_sensor.dhw_pump",
      boost: "button.dhw_boost",
    },
    circuits: [radiators, underfloor],
  },
  "dhw-dual": {
    type: "custom:heatpump-flow-card",
    layout: "dhw-dual",
    title: "Without PV and solar thermal",
    heatpump,
    buffer,
    dhw: {
      name: "Hot water",
      entity: "switch.hot_water",
      temp: "sensor.dhw_temperature",
      target_temp: "number.dhw_setpoint",
      pump: "binary_sensor.dhw_pump",
      boost: "button.dhw_boost",
    },
    circuits: [radiators, underfloor],
  },
  "pv-dual": {
    type: "custom:heatpump-flow-card",
    layout: "pv-dual",
    title: "With PV, without solar thermal",
    heatpump,
    buffer,
    pv: { name: "Photovoltaics", power: "sensor.pv_power", battery: "sensor.battery_soc" },
    circuits: [radiators, underfloor],
  },
  circuits: {
    type: "custom:heatpump-flow-card",
    layout: "full",
    title: "Four circuits, each with its own state",
    pv: false,
    solar: false,
    dhw: false,
    heatpump,
    buffer,
    circuits: [
      {
        name: "Heating circuit A",
        type: "radiator",
        mode: "select.circuit_a_mode",
        pump: "binary_sensor.circuit_a_pump",
        flow_temp: "sensor.circuit_a_flow",
        return_temp: "sensor.circuit_a_return",
        room_temp: "sensor.living_room_temperature",
      },
      {
        name: "Heating circuit B",
        type: "underfloor",
        mode: "select.circuit_b_mode",
        pump: "binary_sensor.circuit_b_pump",
        flow_temp: "sensor.circuit_b_flow",
        return_temp: "sensor.circuit_b_return",
        room_temp: "sensor.bathroom_temperature",
      },
      {
        name: "Heating circuit C",
        type: "underfloor",
        mode: "select.circuit_c_mode",
        pump: "binary_sensor.circuit_c_pump",
        flow_temp: "sensor.circuit_c_flow",
      },
      {
        name: "Heating circuit D",
        type: "fancoil",
        mode: "select.circuit_d_mode",
        pump: "binary_sensor.circuit_d_pump",
        flow_temp: "sensor.circuit_d_flow",
      },
    ],
  },
  advanced: {
    type: "custom:heatpump-flow-card",
    layout: "dual",
    title: "Without a buffer tank, four circuits",
    buffer: false,
    flow_speed: 1.4,
    heatpump,
    dhw: {
      name: "Hot water",
      entity: "switch.hot_water",
      temp: "sensor.dhw_temperature",
      target_temp: "number.dhw_setpoint",
      pump: "binary_sensor.dhw_pump",
      boost: "button.dhw_boost",
    },
    circuits: [
      radiators,
      underfloor,
      { name: "Fan coil, office", type: "fancoil", flow_temp: "sensor.circuit_a_flow", pump: "binary_sensor.circuit_a_pump" },
      { name: "Pool heating", type: "pool", flow_temp: "sensor.circuit_b_flow", return_temp: "sensor.circuit_b_return", pump: "binary_sensor.solar_pump" },
    ],
  },
  compact: {
    type: "custom:heatpump-flow-card",
    layout: "compact",
    title: "Heating, compact",
    heatpump,
    buffer,
    circuits: [radiators],
  },
  single: {
    type: "custom:heatpump-flow-card",
    layout: "single",
    heatpump,
    buffer,
    circuits: [underfloor],
  },
  dual: {
    type: "custom:heatpump-flow-card",
    layout: "dual",
    title: "Heat pump and heating circuits",
    heatpump,
    buffer,
    circuits: [radiators, underfloor],
  },
  full: {
    type: "custom:heatpump-flow-card",
    layout: "full",
    title: "Heating plant",
    heatpump,
    buffer,
    dhw: {
      name: "Hot water",
      entity: "switch.hot_water",
      temp: "sensor.dhw_temperature",
      target_temp: "number.dhw_setpoint",
      pump: "binary_sensor.dhw_pump",
      boost: "button.dhw_boost",
    },
    pv: {
      name: "Photovoltaics",
      // four inverters and two batteries, folded into one value each
      power: [
        "sensor.pv_inverter_1",
        "sensor.pv_inverter_2",
        "sensor.pv_inverter_3",
        "sensor.pv_inverter_4",
      ],
      battery: ["sensor.battery_1_soc", "sensor.battery_2_soc"],
    },
    solar: {
      name: "Solar thermal",
      collector_temp: "sensor.collector_temperature",
      flow_temp: "sensor.solar_flow_temperature",
      pump: "binary_sensor.solar_pump",
      yield: "sensor.solar_yield",
      return_temp: "sensor.solar_return_temperature",
    },
    circuits: [radiators, underfloor],
  },
};
